name: Sync with Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy-to-hf-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Push to Hugging Face Space
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git clone https://__token__:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/BashirG/SkipLegalProject space_repo
          rsync -av --exclude='.git' ./ space_repo/
          
          cd space_repo
          git add .
          git commit -m "Sync from GitHub" || echo "No changes to commit"
          git push
